<!DOCTYPE html>
<?php 
$escape = $this->plugin('escapeHtml');
?>
<html>
<head>
<style>
img {
float: left;
margin: 3px;
}

div#text {
float: right;
width: 240px;
}

div#text h1 {
margin-top: 0px;
}
</style>

</head>
<body>
    <div style="width: 450px">

        <div id='text'>
            <h1><a href='<?php echo $item->siteUrl($siteSlug, true); ?>'><?php echo $item->displayTitle(); ?></a></h1>
            <p>
            <?php echo $item->displayDescription();?>
            </p>
        </div>
        <?php
            if ($primaryMedia = $item->primaryMedia()) {
                $image = $escape($primaryMedia->thumbnailUrl('square'));
                echo "<img src='$image'></img>";
            }
        ?>
    </div>
</body>
</html>