<!DOCTYPE html>
<?php
$escape = $this->plugin('escapeHtml');
?>
<html>
<head>
    <style>
        img {
            float: left;
            margin: 3px;
        }

        div#text {
            float: right;
            width: 240px;
        }

        div#text h1 {
            margin-top: 0px;
        }
    </style>
</head>
<body>
<div style="width: 450px">
    <div id='text'>
        <h1><a href='<?php echo $itemSet->siteUrl($siteSlug, true); ?>'><?php echo $itemSet->displayTitle(); ?></a></h1>
        <p>
            <?php echo $itemSet->displayDescription();?>
        </p>
    </div>
    <?php
    if ($thumbnail = $itemSet->thumbnail()) {
        $image = $escape($thumbnail->assetUrl());
        echo "<img src='$image'></img>";
    }
    ?>
</div>
</body>
</html>