<!DOCTYPE html>
<?php
$escape = $this->plugin('escapeHtml');
?>
<html>
<head>
<style>
img {
float: left;
margin: 3px;
}

div#text {
float: right;
width: 240px;
}

div#text h1 {
margin-top: 0px;
}
</style>

</head>
<body>
    <div style="width: 450px">

        <div id='text'>
<h1><a href='<?php echo $this->page->siteUrl(); ?>'><?php echo $this->page->title(); ?></a></h1>
        </div>

        <?php
        
        $blocks = $this->page->blocks();
        foreach ($blocks as $block) {
            $attachments = $block->attachments();
            foreach($attachments as $attachment) {
                $item = $attachment->item();
                if ($primaryMedia = $item->primaryMedia()) {
                    $image = $escape($primaryMedia->thumbnailUrl('square'));
                    echo "<img src='$image'></img>";
                    break 2;
                }
            }
        }
        ?>
    </div>
</body>
</html>