<ul id='sharing-buttons'>
<li id='sharing-fb' class='sharing-button'><?php echo $translator->translate('Facebook'); ?></li>
<li id='sharing-twitter' class='sharing-button'><?php echo $translator->translate('Twitter'); ?></li>
<li id='sharing-pinterest' class='sharing-button'><?php echo $translator->translate('Pinterest'); ?></li>
<li id='sharing-tumblr' class='sharing-button'><?php echo $translator->translate('Tumblr'); ?></li>
<li id='sharing-email' class='sharing-button'><?php echo $translator->translate('Email'); ?></li>
</ul>